[preview]
  # extra_args = []
# show_at_bottom = true
show_at_start = true
width_percentage = 50.0
width_increment_percentage = 5.0
# experimental_log_batching_enabled = true

[keys]
# cancel = ["q"]
# escape = ["esc"]

  [keys.preview]
    scroll_up = ["ctrl+b"]
    scroll_down = ["ctrl+f"]


[ui]
auto_refresh_interval=4
tracer.enabled = true

[[actions]]
name = "duplicate"
desc = "duplicate on top of current branch"
lua = '''
local diff = jj("duplicate", "-B", "@", "-r", context.change_id())
flash("ran a duplicate")
'''

[[actions]]
name = "my-action"
lua = 'flash("hello")'

# [custom_commands]
# # duplicate 
# # "resolve vscode" = { key = ["R"], args = ["resolve", "--tool", "vscode"], show = "interactive" }
# "revert" = { key = [ "R" ] , args = [ "revert", "-r", "$change_id" ] }
# "tug" = { key = ["ctrl+t"], args = ["bookmark", "move", "--from", "closest_bookmark($change_id)", "--to", "closest_pushable($change_id)"] }
# [[bindings]]
# action = "my-action"
# key = "H"
# scope = "revisions"

[[bindings]]
action = "duplicate"
key = "H"
# desc = "Duplicate"
# scope => where the bindings are active
scope = "revisions"


[revisions]
# log_batching = false
# template = 'builtin_log_compact' # overrides jj's templates.log
# revset = ""  # overrides jj's revsets.log
