[preview]
  # extra_args = []
# show_at_bottom = true
show_at_start = true
width_percentage = 50.0
width_increment_percentage = 5.0
# experimental_log_batching_enabled = true

[keys]
# cancel = ["q"]
# escape = ["esc"]

  # [keys.preview]
  #   scroll_up = ["ctrl+b"]
  #   scroll_down = ["ctrl+f"]


[ui]
auto_refresh_interval=4
tracer.enabled = true

[[actions]]
name = "duplicate"
desc = "duplicate on top of current branch"
# 
lua = '''
local change_id = context.change_id()
local diff = jj("duplicate", "-B", "@", "-r", change_id)
flash("Duplicated ".. change_id .. " over "..revisions.current())

'''

# [[actions]]
# name = "bookmark-create-modal"
#   config.action("create bookmark", function()
#     jj("bookmark", "create", input())
#     revisions.refresh()
#   end, {
#     seq = { "\\", "c" },
#     scope = "revisions",
#   })
[[actions]]
name = "my-action"
lua = 'flash("hello")'

# [custom_commands]
# # duplicate 
# # "resolve vscode" = { key = ["R"], args = ["resolve", "--tool", "vscode"], show = "interactive" }
# "revert" = { key = [ "R" ] , args = [ "revert", "-r", "$change_id" ] }
# "tug" = { key = ["ctrl+t"], args = ["bookmark", "move", "--from", "closest_bookmark($change_id)", "--to", "closest_pushable($change_id)"] }
# [[bindings]]
# action = "my-action"
# key = "H"
# scope = "revisions"

[[bindings]]
action = "duplicate"
# key = "d"
seq = [ "d", "u"]
# desc = "Duplicate"
# scope => where the bindings are active
scope = "revisions"


[[bindings]]
key = "ctrl+f"
action = "ui.preview_scroll_down"
scope = "ui.preview"
desc = "scroll down" 
# { key = "ctrl+f", action = "file_search.preview_half_page_down", scope = "file_search", desc = "preview half down" },

[[bindings]]
key = "ctrl+b"
action = "ui.preview_scroll_up"
scope = "ui.preview"
desc = "scroll up" 

[revisions]
# log_batching = false
# template = 'builtin_log_compact' # overrides jj's templates.log
# revset = ""  # overrides jj's revsets.log
