; specifically created as an embedding llama-instance

[*]
port = 8081
embedding = on
; Increased ubatch size because of
; 19.43.653.521 D srv    operator(): client request thread ended
; 19.43.653.535 D srv    operator(): http: streamed chunk: {"error":{"code":500,"message":"input (529 tokens) is too large to process. increase the physical batch size (current batch size: 512)","type":"server_error"}}
; Traceback (most recent call last):
;   File "/home/teto/plugins/avante.nvim/py/rag-service/.venv/lib/python3.11/site-packages/openai/_base_client.py", line 1043, in _request
;     response.raise_for_status()
;   File "/home/teto/plugins/avante.nvim/py/rag-service/.venv/lib/python3.11/site-packages/httpx/_models.py", line 829, in raise_for_status
;     raise HTTPStatusError(message, request=request, response=self)
; httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'http://localhost:8081/v1/embeddings'

ubatch-size = 1024
; useless
; api-key seems mandatory for pi ?
api-key = toto 
models-dir = /home/teto/llama-models
; only keep  '--models-max' loaded in memory
models-max = 1
log-colors = on
log-file = /tmp/llama-embed.log
mmproj-offload = off

[embedding-gemma-300]
hf = unsloth/embeddinggemma-300m-GGUF

