#+title: how to use this repo
#+author: teto
#+NAME: demo
#+LINK: nixos-anywhere https://github.com/nix-community/nixos-anywhere
#+LINK: disko https://github.com/nix-community/disko
#+LINK: sops-nix-github https://github.com/Mic92/sops-nix
#+LINK: haumea https://github.com/nix-community/haumea

This is *tetos*, teto's OS, nixos-based, conceived by me for me.
It contains the configuration for my machines/servers.
I make it public because I love libre software and this makes sharing snippets easier.
Dont expect to be able to use this repo as it is a spaghetti of hacks and relies on forks of nixpkgs and home-manager.

* a few highlights
- I rely on [[nixos-anywhere][nixos-anywhere]] + [[disko][disko]] to deploy new machines. For local deployements, I use one machine as a PXE server to bootstrap install from a nicer environment
- My main difficulty when deploying machines is handling secrets. I dont want to put git secrets - even cyphered - online.
This is why my *nixosConfigurations* can be built __with__ and __without__ secrets depending on a boolean `withSecrets` forwarded via `specialArgs`.
This lets me deploy a machine with most of my customizations before migrating my secrets and run a final deployement with all secrets available.
My secrets are handled with [[sops-nix-github][sops-nix]] and not gitted (no way I would put those public).
- the flake exposes `nixosModules` along with `homeModules`. I name configurations that can be shared between hosts "profiles" (some would call it "roles") so the flake exposes `nixosProfiles` as well as `homeProfiles`
- nix packages/modules/profiles are autoloaded according to the folder hierarchy. This is made possible by [[haumea][haumea]].
I dont necessarily recommand haumea though because it can lead to some hard to diagnose error messages and while elegant it makes sideeffects harder to track down IMO.
- automated generation of ssh client configuration from the various nixosConfigurations ssh servers


If you scroll a bit, you will find sparse tutorials on how to deploy both on a LAN (PXE) or remotely (e.g. VPS). Kudos to [[nixos-anywhere][nixos-anywhere]] and [[disko]] for making this easier than ever.

* home

This folder contains my customizations for:
- [[https://dystroy.org/broot/][broot]] file explorer
- [[https://github.com/jarun/Buku][buku]]: a cli bookmark manager
- clerk (to control mpd via rofi)
- [[https://github.com/FontManager/font-manager][font-manager]] the best font manager I could find
- [[https://fcitx-im.org/wiki/Fcitx_5][fcitx5]] (input method mechanims, e.g. to type japanese from your qwerty keyboard)
- [[https://github.com/rycee/home-manager/][home-manager]] to generate dotfiles from nix
- htop / btop
- [[https://gitlab.freedesktop.org/emersion/kanshi]][[kanshi]]: a monitor manager for wayland
- [[way-displays]][[]] in the same vein
- [[https://github.com/Alexays/Waybar][waybar]] sway bar
- [[https://github.com/pimutils/khard][khard]] (a carddav CLI)
- [[https://github.com/pimutils/khal][khal]] (a calendar CLI)
- mpd (configuration files to run this music server as a user)
  - [[rmpc][https://github.com/mierak/rmpc/]] A fantastic rust+tui player
  - [[euphonica][https://github.com/htkhiem/euphonica]] a beautiful gtk gui
  - ncmpcpp (mpd console player)
- [[https://marlam.de/msmtp/news][msmtp]] (MSA: Mail Sending Agent)
- [[https://mierak.github.io/rmpc/]][rmcp]] (mpd console player)
- [[https://github.com/neovim/neovim][neovim]] (fork of vim)
- [[https://newsboat.org/][newboat]] (RSS reader, fork of newsbeuter)
- [[www.notmuch.org][notmuch]] (to tag mails)
   - [[https://github.com/purebred-mua/purebred][purebred]] (terminal MUA)
   - [[https://github.com/pazz/alot][alot]] (MUA: Mail User Agent, like mutt)
   - [[https://github.com/astroidmail/astroid][astroid]] (MUA with a GUI)
   - [[https://neomutt.org][neomutt]] (Mail User Agent)
- [[qutebrowser][www.qutebrowser.org]] (vim like browser)
- [[https://github.com/DaveDavenport/rofi][rofi]] (a dmenu-like interactive prompt, works with clerk/i3 etc...)
- [[https://starship.rs/][starship]] (prompt manager)
- nssxiv (image viewer)
- [[www.swaywm.com][sway]] (wayland window manager)
- [[https://sw.kovidgoyal.net/kitty/][kitty]] (terminal)
- [[https://wezfurlong.org/][wezterm]] (terminal)
- [[https://github.com/jonas/tig][tig]] (a git history reader)
- tmux (terminal multiplexer)
- [[https://github.com/tio/tio][tio]] a serial device tool
- [[https://vifm.info/][vifm]] (ranger-like, file explorer)
- [[https://github.com/vimus/vimus][vimus]] (or vimpc ? mpd player)
- [[https://www.visidata.org/][visidata]] (for data analysis, csv/json/pcap/... reader)
- [[https://weechat.org/][weechat]] (Irc client)
- [[https://github.com/sxyazi/yazi][yazi]] a TUI file manager in rust, much faster than ranger or joshuto, just amazing
- zsh (alternative to bash)


* nixos-anywhere install via PXE

We use [[nixos-anywhere][nixos-anywhere]] + [[disko][disko]], aka we need a SERVER machine in the same LAN as the NEW machine to deploy from. 
1. SERVER: Enable the pixiecore service
2. NEW: start via PXE
3. NEW: echo LUKS_PASSWORD > /tmp/secret.key
4. SERVER: run `just bootstrap-desktop`

* nixos-anywhere remote/vps install 

For OVH: follow [[https://edouard.paris/notes/install-nixos-on-an-ovh-vps-with-nixos-anywhere/][this ovh]] guide.
For gandi it's easy.


#+BEGIN_SRC shell
just bootstrap-vps <vps-address>
#+END_SRC


* bootstrap from machine itself (ie, from scratch)

As long as flakes are not supported natively, you need to:
#+BEGIN_SRC shell
# when not setting #my-machine, defaults to hostname
# deploy a first generation without any secrets but in my favorite environment
$ nixos-rebuild switch --flake 'github:teto/home#laptop' --sudo --option accept-flake-config true --option extra-experimental-features 'nix-command flakes'
$ just stow-config stow-home stow-local
# once you've moved on the secrets to where they must be, you can deploy the final configuration
$ nixos-rebuild switch --flake 'github:teto/home#laptop-with-secrets' --use-remote-sudo --option accept-flake-config true --option extra-experimental-features 'nix-command flakes'
#+END_SRC


* Approach to handling secrets

  Nix writes everything world-readable so you dont want to embed passwords in .nix files.

  ** information you prefer to hide but won't seppuku if discovered...

  ... are handled via git-crypt in the repo.

  ** Infrastructure secrets

  The solution I adopted is [[sops-nix-github][sops-nix]] which reads secrets from sops files.

  *** How to securely load those secrets in systemd units ?

  With sops, you could create /run/secrets/email_password and have your service pick it up.
  Set the proper owner to avoid anyone being able to read it.

  One further security can be to rely on systemd-creds.
  LoadCredentialEncrypted

   /home/teto/.config/systemd/user/mbsync.service.d/override.conf

  ** Most intimate secrets

  you wont find on this repo. I handle them via [[https://www.passwordstore.org/][pass]] and transfer them
  manually on my machines via the tool in the next section.


* How to transfer state

Some secrets can't be shared reliably on the repository so they need to be
transferred.


** How to transfer secrets from another machine

* age key for sops
* git crypt key to decypher secrets saved in the repo

TODO mention termscp or yazi + rsync ?

On the old machine:
#+BEGIN_SRC
$ wormhole send ~/.gnupg
$ wormhole send ~/.password-store 
$ wormhole send ~/.ssh
$ wormhole send ~/home/secrets
#+END_SRC

On the new machine:
#+BEGIN_SRC
$ just receive-secrets
tar xvf -C ~/.gnupg/ gnupg.tar
...
#+END_SRC

** How to recover this repo cyphered files

Get git-crypt do decypher the files
Retreive the key (possibly from an existing deployement via `git-crypt export-key toto.key`) and use
it on the new deployement via:
#+BEGIN_SRC sh 
$ git-crypt unlock secrets/git-crypt-teto.key
#+END_SRC
should unlock the files.

NOTE: nixos doesnt seem to work out of the box with git-crypt [[https://github.com/NixOS/nix/issues/5260][anymore]], 
 the secret is to leave your repo in a dirty state so that nix sees the unlocked secrets.nix !

* Font management

fontconfig

* Debug neovim config ?

You can see the resulting config via:

#+BEGIN_SRC
nix repl . --override-input nixpkgs github:nixos/nixpkgs
nixosConfigurations.laptop.config.home-manager.users.teto.programs.neovim.finalPackage.XXX
#+END_SRC

** tips for reinstallation

Apart from dd, to create a windows installer USB key, unetbootin worked the best:
`nix shell nixpkgs#unetbootin`


Tell me what to do please


