# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  # does not work anymore with flakes
  # imports =
  #   [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
  #   ];

  # replace it in the flake with
  # modules = [ pkgs.nixosModules.notDetected ];

  boot.initrd.availableKernelModules = [
  "nvme" "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" 
   
  ];
  boot.initrd.kernelModules = [ 
  "nvme" "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" 

  ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "vfat" "xfs" "cifs" "ntfs" ];

  # to remove "TSC_DEADLINE disabled due to Errata;
  # please update microcode to version: 0x22"
  hardware.cpu.intel.updateMicrocode = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/01435119-f2c1-4316-b828-489a76df79c6";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CA0D-A5E4";
      fsType = "vfat";
    };


  fileSystems."/mnt/ext" =
    {
      device = "/dev/disk/by-uuid/d118729e-bc3d-4e02-bf6b-f0cb54fef2a1";
      fsType = "ext4";
      # "exec"
      # user disables exec
      options = [ "defaults" "user" "exec" "nofail" ];
    };

  # fileSystems."/mnt/ntfs" =
  #   {
  #    # ntfs-3g doesn't seem to like a path by uuid
  #     # device = "/dev/disk/by/uuid/65F4B09F417BB97C";
  #     device = "/dev/sdb2";
  #     fsType = "ntfs";
  #     # see https://nixos.wiki/wiki/NTFS
  #     options = [ "rw" "uid=teto" "nofail" ];
  #     # options = [ "user", ];
  #   };



  # nix.settings.max-jobs = lib.mkDefault 4;
  # Often used values: "ondemand", "powersave", "performance"
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
