{ config, ... }:
{
  services.postgresqlBackup = {
    enable = true;
    startAt = "*-*-* *:15:00";
    pgdumpOptions = "--no-owner";

    # generate systemd services called "postgresqlBackup-${db}"
    databases = [
      # https://immich.app/docs/administration/backup-and-restore
      config.services.immich.database.name
    ];

    # services.postgresqlBackup.location
    # Path of directory where the PostgreSQL database dumps will be placed.
    # Default: "/var/backup/postgresql"
  };

  services.restic.backups = {
    immich-db-to-backblaze = {
      extraOptions = [
        "sftp.command='ssh backup@host -i /etc/nixos/secrets/backup-private-key -s sftp'"
      ];
      # passwordFile = "/etc/nixos/secrets/restic-password";
      passwordFile = "/var/lib/b2-immich-backup-api-key";
      paths =
        let
          # depends on "IMMICH_MEDIA_LOCATION=/var/lib/immich"
          UPLOAD_LOCATION = "/var/lib/immich";
        in
        [
          # backup of the immich DB generated by services.postgresqlBackup 
          "/var/backup/postgresql"

          # backup of immich data (not generated)
          # see https://immich.app/docs/administration/backup-and-restore#filesystem
          "${UPLOAD_LOCATION}/library"
          "${UPLOAD_LOCATION}/profile"
          "${UPLOAD_LOCATION}/upload"
        ];
      repository = "sftp:backup@host:/backups/home";
      timerConfig = {
        OnCalendar = "00:05";
        RandomizedDelaySec = "5h";
      };
    };
  };

  # services.borgbackup.jobs
}
