{ config, secrets, ... }:
{
  # if you want to get a notification
  # https://www.arthurkoziel.com/restic-backups-b2-nixos/
  services.restic.backups = {
    immich-db-to-backblaze = {
      # under which user to run. Defaults to root
      user = "teto";
      extraOptions = [
        # "sftp.command='ssh backup@host -i /etc/nixos/secrets/backup-private-key -s sftp'"
      ];

      # that's where our provider (backblaze) credentials go
      environmentFile = config.sops.secrets."restic/backblaze_backup_immich_credentials".path;
      # this is the restic password
      passwordFile = config.sops.secrets."restic/backup_immich_repo_password".path;
      # passwordFile = "/var/run/secrets/restic/backup_immich_repo_password";
      paths =
        let
          # TODO see if we cant retreive it from the service configuration
          # depends on "IMMICH_MEDIA_LOCATION=/var/lib/immich"
          # config.services.immich.dataDir;
          UPLOAD_LOCATION = "/var/lib/immich";
        in
        [
          # backup of the immich DB generated by services.postgresqlBackup
          "${UPLOAD_LOCATION}/backups"

          # backup of immich data (not generated)
          # see https://immich.app/docs/administration/backup-and-restore#filesystem
          "${UPLOAD_LOCATION}/library"
          "${UPLOAD_LOCATION}/profile"
          "${UPLOAD_LOCATION}/upload"
        ];
      # pruneOpts = [
      #   "--keep-daily 7"
      #   "--keep-weekly 4"
      #   "--keep-monthly 2"
      #   "--keep-yearly 0"
      # ];

      # backupPrepareCommand = "${pkgs.restic}/bin/restic unlock";
      createWrapper = true;
      initialize = true; # create restic repo if it doesn't exist
      # could we check the service at buildtime ?
      repository = secrets.backblaze.immich-backup-bucket;

      # repositoryFile
      timerConfig = {
        # daily
        OnCalendar = "03:00";
        RandomizedDelaySec = "1h";
        # OnUnitActiveSec = "1d";

        # Persistent = true;
        # NB: the option Persistent=true triggers the service
        # immediately if it missed the last start time
      };

    };
  };
}
