/*
  pkgs/development/lua-modules/generated-packages.nix is an auto-generated file -- DO NOT EDIT!
  Regenerate it with: nix run nixpkgs#luarocks-packages-updater
  You can customize the generated packages in pkgs/development/lua-modules/overrides.nix
*/

{
  stdenv,
  lib,
  fetchurl,
  fetchgit,
  callPackage,
  ...
}:
final: prev: {
  lsqlite3 = callPackage (
    {
      buildLuarocksPackage,
      fetchurl,
      fetchzip,
      luaAtLeast,
      luaOlder,
    }:
    buildLuarocksPackage {
      pname = "lsqlite3";
      version = "0.9.6-1";
      knownRockspec =
        (fetchurl {
          url = "mirror://luarocks/lsqlite3-0.9.6-1.rockspec";
          sha256 = "1wb51lsfllmbzrjfl0dzxpg597nd54nn06c9plpvqwwjz4l9lrjf";
        }).outPath;
      src = fetchzip {
        url = "https://lua.sqlite.org/home/zip/lsqlite3_v096.zip?uuid=v0.9.6";
        sha256 = "060qmdngzmigk4zsjq573a59j7idajlzrj43xj9g7xyp1ps39bij";
      };

      disabled = luaOlder "5.1" || luaAtLeast "5.5";

      meta = {
        homepage = "http://lua.sqlite.org/";
        description = "A binding for Lua to the SQLite3 database library";
        maintainers = with lib.maintainers; [ mrcjkb ];
        license.fullName = "MIT";
      };
    }
  ) { };

  luarocks-tag-release = callPackage (
    {
      buildLuarocksPackage,
      dkjson,
      fetchurl,
      fetchzip,
      lua-curl,
      luaOlder,
    }:
    buildLuarocksPackage {
      pname = "luarocks-tag-release";
      version = "7.2.0-1";
      knownRockspec =
        (fetchurl {
          url = "mirror://luarocks/luarocks-tag-release-7.2.0-1.rockspec";
          sha256 = "03bwmgajdfsqc3xhfq7z2rsgwz7in8m2mqh3xzn38lqm8g671fdl";
        }).outPath;
      src = fetchzip {
        url = "https://github.com/nvim-neorocks/luarocks-tag-release/archive/v7.2.0.zip";
        sha256 = "04wnk1wi8kycwxa2ad80ydybymg3lfv3d5nwx18vqgzwrhzapyni";
      };

      disabled = luaOlder "5.1";
      propagatedBuildInputs = [
        dkjson
        lua-curl
      ];

      meta = {
        homepage = "https://github.com/nvim-neorocks/luarocks-tag-release";
        description = "Luarocks release workflow for GitHub";
        maintainers = with lib.maintainers; [ mrcjkb ];
        license.fullName = "AGPL-3.0";
      };
    }
  ) { };

}
# GENERATED - do not edit this file
