# https://ideatrash.net/2020/06/weekend-project-whole-house-and-streaming-audio-for-free-with-mpd.html
audio_output {
  type "httpd"
  name "my http stream"
  # encoder "lame"
  port "8000" # this is different than mpd port, just select the correct output from the client
  # bitrate "256" #kbps
  # format'
  always_on   "yes"
}

replaygain         "track"
replaygain_preamp       "0"
volume_normalization        "yes"

# We are enabling this for Snapclient
zeroconf_enabled        "yes"
# You can use whatever name you like here.
zeroconf_name           "MPD"
