# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]

# todo generate some via nix ?
import = [
  # "rocks-local.toml", # Paths are relative to the rocks.toml file directory by default
  # "~/my-rocks.toml", # Path expansion is supported through vim.fn.expand
  # "/home/user/my-rocks.toml", # Absolute paths are supported
]


[config]
plugins_dir = "plugins/"

[dev]
path = "/home/teto/plugins"

# https://github.com/lumen-oss/rocks-lazy.nvim#lua-configuration
[rocks_lazy]
# This is a subdirectory (relative to nvim/lua) to search for plugin specs. In this example, you can add a lua/lazy_specs/ directory to your nvim config, with a lua script for each plugin.
import = "lazy_specs/"

# [rocks-git]
# path = "/home/teto/.local/share/nvim/site/pack/rocks"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.49.0"
"rocks-git.nvim"= "2.6.0"
"rocks-config.nvim" = "3.2.0"
"rocks-dev.nvim" = "1.8.1"
"rocks-lazy.nvim" = "1.2.2"

# "haskell-tools.nvim" = "10.0.1"

# needed the patch from https://github.com/nvimtools/none-ls.nvim/pull/277/
"none-ls.nvim" = "scm"
"none-ls-extras.nvim" = "scm"

# remove now that it's nix installed
# "lualine.nvim" = "scm"

# i seldomly use it
# "trouble.nvim" = "scm"

"lsp_signature.nvim" = "0.3.1"
friendly-snippets = "scm"
# "haskell-snippets.nvim" = "1.4.4"



# treesitter is such a mess that I removed it
# disabled because of Error was: ....config/nvim/lua/plugins/nvim-treesitter-textobjects.lua:1: module 'nvim-treesitter.configs' not found:No LuaRocks module found for nvim-treesitter.configs
# nvim-treesitter-textobjects = "scm"
# "rocks-treesitter.nvim" = "1.0.3"

# works with hop.nvim to jump somewhere in the AST (depends on hop.nvim so not that interesting)
# nvim-treehopper = "scm"
# tree-sitter-haskell = "0.0.40"
# # tree-sitter-hurl = "0.0.31"
# tree-sitter-html = "0.0.40"
# tree-sitter-xml = "0.0.43"

# "lspkind.nvim" = "scm"
# "modicator.nvim" = "scm"

# todo bind it to rest-nvim in nixpgs 
# "rest.nvim" = "3.13.0"


# nvim-bqf= "1.1.1"

# TODO marks-nvim ?

menu= "scm"
"indent-blankline.nvim" = "3.9.1"
# "llm.nvim"= "scm"
# volt is a UI library
volt= "scm"
# orgmode = "0.7.1"
# neogit = "2.0.0"
"gitsigns.nvim"= "2.1.0"

# there is a bug where it creates home/teto folders everywhere
# "typescript-tools.nvim" = "scm"

# "rest.nvim" = "3.13.0"
# magick = "1.6.0"
# "image.nvim" = "1.3.0"

# for the image preview , hopefully we can dot without soon with nvim 0.13
"snacks.nvim" = "2.31.0"

# how to get rid of it:

# hopefully loads only for markdown
"render-markdown.nvim" = "8.13.0"

# disabled because of this bug https://github.com/neovim/neovim/issues/37317
# possible fix at https://github.com/Bekaboo/dropbar.nvim/pull/280
# "dropbar.nvim" = "14.2.1"
nvim-treesitter-context = "1.0.0"
# nvim-dap = "0.10.0"
# neotest = "5.19.0"
# neotest-busted = "1.3.1"

# auto-session = "2.5.1"
"vim-startuptime"= "4.6.1"
"grug-far.nvim"= "1.6.78"
"yazi.nvim"= "14.0.0"
"quicker.nvim" = "1.5.1"

[plugins."rikai.nvim"]
dev = true

[plugins."hacker.nvim"]
git = "letieu/hacker.nvim"
rev = "7cf7189f488ea3a81d4b75b44d7c38663475c7a3"
opt = true

[plugins."baleia.nvim"]
git = "m00qek/baleia.nvim"
rev = "v1.4.0"

[plugins."statuscol.nvim"]
git = "luukvbaal/statuscol.nvim"
rev = "887b8a03ea3804628505c9002fd07bd06a3db2e0"

[plugins."fcitx.nvim"]
git = "h-hg/fcitx.nvim"
rev = "c8543d72adf02a557722847c5d263171ec5c9bb4"

[plugins."tidal.nvim"]
git = "https://github.com/grddavies/tidal.nvim"
rev = "fa4673e181e18fd1719ae17a1d4f4ecce2de37aa"
opt = true

[plugins."fzf-lua-frecency.nvim"]
git = "elanmed/fzf-lua-frecency.nvim"
rev = "5726403e132fe8699d670c7ef8d59dbed887b4e6"

# [plugins."tiny-inline-diagnostic.nvim"]
# git = "rachartier/tiny-inline-diagnostic.nvim"
# rev = "6264451f14119d63a52580e5198d6baf8518b0b2"
#
# [plugins."jj.nvim"]
# git = "nicolasgb/jj.nvim"
# rev = "v0.7.1"
#
# [plugins."jujutsu.nvim"]
# git = "yannvanhalewyn/jujutsu.nvim"
# rev = "61239312730b3f51441596bdadab7e3578987592"
#
# [plugins."jiejie.nvim"]
# git = "jceb/jiejie.nvim"
# rev = "6a3a3598e6e015cfd3f1f447c257314972030e1b"

# [plugins."opencode.nvim"]
# git = "nickjvandyke/opencode.nvim"
# rev = "v0.6.0"

[plugins.blink-cmp-git]
git = "kaiser-yang/blink-cmp-git"
rev = "v3.0.0"

[plugins.blink-cmp-avante]
git = "kaiser-yang/blink-cmp-avante"
rev = "v0.1.0"
branch = "master"

[plugins."kitty-scrollback.nvim"]
git = "mikesmithgh/kitty-scrollback.nvim"
rev = "v9.2.1"

[plugins."tiny-cmdline.nvim"]
git = "rachartier/tiny-cmdline.nvim"
rev = "e247d9ee4c980734f8f8bf616d31e0ab7c27485d"

[plugins.nvim-biscuits]
git = "code-biscuits/nvim-biscuits"
rev = "d93dcdee3a3dfd5101785447658e744f153957db"

[plugins.vim-matchup]
git = "andymass/vim-matchup"
rev = "v0.8.0"

[plugins."diffview-plus.nvim"]
git = "dlyongemallo/diffview-plus.nvim"
rev = "v0.37"

[plugins.vlime]
git = "vlime/vlime"
rev = "v0.4.0"

# [plugins."git-rebase-auto-diff.nvim"]
# git = "yutkat/git-rebase-auto-diff.nvim"
# rev = "6fd2f5ba63828e5c4fd59bb1b75ef7525a5ce39f"

# [plugins."blink.compat"]
# git = "saghen/blink.compat"
# rev = "v2.5.0"

# [plugins."treewalker.nvim"]
# git = "aaronik/treewalker.nvim"
# rev = "4992fa9d27792b7a573e4545c9b2c4e61aba4f44"

#
# [plugins."hunk.nvim"]
# git = "julienvincent/hunk.nvim"
# rev = "v1.9.0"
#
