#!/bin/bash
#echo $(dirname ${BASH_SOURCE:-$0})
notmuch tag --batch --input="$XDG_CONFIG_HOME/notmuch/ietf"
notmuch tag --batch --input="$XDG_CONFIG_HOME/notmuch/foss"
notmuch tag --batch --input="$XDG_CONFIG_HOME/notmuch/pres"
#notmuch tag --batch --input="$XDG_CONFIG_HOME/notmuch/security"
