# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/443ce6b0-e43e-43e6-9d10-c0c6293ccf66";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/ebbfc6ca-a0f0-4b8b-ac1e-7a2b4390d72c"; }
    ];

  fileSystems."/mnt/ext4" =
    { device = "/dev/sda1";
      fsType = "ntfs";
      # see https://nixos.wiki/wiki/NTFS
      options = [ "rw" "uid=teto"];
    # options = [ "user", ];
    };

  fileSystems."/mnt/ntfs" =
    {
      device = "/dev/sda2";
      fsType = "ntfs";
      # see https://nixos.wiki/wiki/NTFS
      options = [ "rw" "uid=teto"];
    # options = [ "user", ];
    };



  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
