# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [
    "xhci_pci" "ehci_pci" "ahci" "firewire_ohci" "usbhid" "sd_mod" "sr_mod" "sdhci_pci" 
  ];
  boot.kernelModules = [
    "kvm-intel"
    "b43"
  ];
  boot.extraModulePackages = [
    config.boot.kernelPackages.broadcom_sta
  ];


  boot.blacklistedKernelModules = [ "wl" ];
  # a contender is https://wireless.wiki.kernel.org/en/users/drivers/b43
  # networking.enableB43Firmware = true;
  # hardware.firmware = [ pkgs.b43Firmware_6_30_163_46 ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/91ccf165-de06-44f1-9dc8-652a5f7d92cf";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/745E-30ED";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d02fb2d3-e82f-4940-9a32-85d389bb655b"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = "powersave";
}
