ctrl+q quit
s screenshot
h show_text "hello world"

# uosc config
mbtn_right  script-binding uosc/menu
menu        script-binding uosc/menu

# https://www.youtube.com/watch?v=QAh8LoBLXPs
p script-message cycle-profile

V cycle secondary-sub-visibility

# Mod+j cycle secondary-sid
# Alt+J cycle secondary-sid down

r      load-input-conf /home/teto/home/config/mpv/input.conf

UP   set secondary-sub-visibility yes
DOWN   set secondary-sub-visibility no

Q  quit-watch-later
#  cycle ontop  #! Toggle on-top
#
# tab  script-binding uosc/toggle-ui
tab         script-binding uosc/load-subtitles  #! Load subtitles
# S 
s           script-binding uosc/subtitles          #! Subtitles
a           script-binding uosc/audio              #! Audio tracks
# q           script-binding uosc/stream-quality     #! Stream quality
p           script-binding uosc/items              #! Playlist
c           script-binding uosc/chapters           #! Chapters
>           script-binding uosc/next               #! Navigation > Next
<           script-binding uosc/prev               #! Navigation > Prev
alt+>       script-binding uosc/delete-file-next   #! Navigation > Delete file & Next
alt+<       script-binding uosc/delete-file-prev   #! Navigation > Delete file & Prev
alt+esc     script-binding uosc/delete-file-quit   #! Navigation > Delete file & Quit
o           script-binding uosc/open-file          #! Navigation > Open file
#           set video-aspect-override no           #! Utils > Aspect ratio > Default
#           set video-aspect-override "16:9"       #! Utils > Aspect ratio > 16:9
#           set video-aspect-override "4:3"        #! Utils > Aspect ratio > 4:3
#           set video-aspect-override "2.35:1"     #! Utils > Aspect ratio > 2.35:1
#           script-binding uosc/audio-device       #! Utils > Audio devices
#           script-binding uosc/editions           #! Utils > Editions
ctrl+s      async screenshot                       #! Utils > Screenshot
alt+i       script-binding uosc/keybinds           #! Utils > Key bindings
O           script-binding uosc/show-in-directory  #! Utils > Show in directory
#           script-binding uosc/open-config-directory #! Utils > Open config directory
#           script-binding uosc/update             #! Utils > Update uosc
# esc         quit                                   #! Quit
