#!/bin/bash

# OSD
dunst&
#owncloud&
volumeicon& 
compton&

#firefox &

## Set startup volume
# set volume
# pactl set-sink-volume 0 '30%' &



## Working shells on workspace 1
#i3-msg workspace 1

#i3-msg layout tabbed
#urxvt256c -name mail -e bash -c "mutt" &
#dunst-checkmail&
