#!/usr/bin/python3
from i3gen import i3ConfigGenerator

cfg = i3ConfigGenerator()

cfg.workspaces = [


]

cfg.add_raw_text("# Generated with i3gen")

cfg.add_module("mediaplayer", "csv/mocp.mediaplayer.csv")
cfg.add_module("volume", "csv/amixer.csv",)
cfg.add_module("focus_win", "csv/arrows.csv",)
cfg.add_module("move_win", "csv/arrows.csv",)
cfg.add_module("layouts", "csv/layouts.csv",)
cfg.add_module("bar", "csv/default_bar.csv")
# TODO move to core modules
cfg.add_module("ws", ws_names=["1:main", "2:web", "3:éditeurs", "4:qemu"])
cfg.add_module("ws_assign", "csv/ws_assign.csv", ws2="plop")
cfg.add_module("ws_goto", "csv/workspaces.csv", ws2="plop")
cfg.add_module("main", "csv/config.csv", ws2="plop")
cfg.add_module("session", )
cfg.add_module("perso", )
# cfg.add_module("change_ws", ws_names=["1: main", "2:web", "3:dev", "4:misc"])
# cfg.add_module("brightness", "csv/arrows.csv",)

cfg.add_mode("r", "resize", "csv/arrows.csv", "csv/hjkl.csv")
cfg.add_mode("m", "monitors", "csv/arrows.csv", )
# cfg.add_mode("r", "resize", "csv/arrows.csv", "csv/hjkl.csv")

# cfg.add_module("perso")

filename = cfg.save()
if cfg.check_conformity(filename):
    cfg.install(filename, check=False, backup=True)
    # pass
    # cfg.restart()
else:
    print("Failed check")
