{
  config,
  pkgs,
  lib,
  withSecrets,
  # dotfilesPath,
  secrets,
  ...
}:
let
  getPasswordCommand = account: lib.strings.escapeShellArgs (lib.getPassword account);
  mailDirBasePath = "${config.home.homeDirectory}/maildir";

  # file generated by generate-addressbook
  addressBookFilename = "${config.xdg.cacheHome}/addressbook.json";

  defaultSendMailCommand = "${pkgs.msmtp}/bin/msmtpq --debug --read-envelope-from --read-recipients";

  accountExtra = {
    alot = {
      # TODO pass mon fichier a moi
      contactCompletion = {
        type = "shellcommand";
        command = "cat ${addressBookFilename}";
        regexp =
          "'\\[?{"
          + ''"name": "(?P<name>.*)", ''
          + ''"address": "(?P<email>.+)", ''
          + ''"name-addr": ".*"''
          + "}[,\\]]?'";
        shellcommand_external_filtering = "False";
      };
    };

  };

  gpgModule = {
    key = "64BB678705EF85ABF7345F69BD024BD9C261596D";
    signByDefault = false;
  };

  fastmail = accountExtra // {
    primary = true;
    userName = secrets.accounts.mail.fastmail_perso.login;
    realName = secrets.users.teto.realName;
    address = secrets.accounts.mail.fastmail_perso.email;

    # fastmail requires an app-specific password
    passwordCommand = getPasswordCommand "perso/fastmail_mc/password";

    gpg = gpgModule;
    flavor = "fastmail.com";

    astroid = {
      enable = false;
    };

    neomutt = {
      enable = true;
      sendMailCommand = defaultSendMailCommand;

      # to avoid adding "Inbox to the command";
      showDefaultMailbox = false;

    };

    # TODO restore
    meli = {
      enable = true;
      # ""jmap
      mailboxAliases = {
        # interesting to see in man meli.conf
        "INBOX" = {
          alias = "Inbox";
          autoload = true;
          # must depend on parent ?
          collapsed = true;
          # silently insert updates
          ignore = false;
          # usage boolean                         (optional) special usage of  this  mailbox.   Valid
          #                             values are:
          #                             -   Normal (default)
          #                             -   Inbox
          #                             -   Archive
          #                             -   Drafts
          #                             -   Flagged
          #                             -   Junk
          #                             -   Sent
          #                             -   Trash

          sort_order = 0;
          # limit in time
          query = "tag:inbox and not tag:killed and date:1y..";
          # subscribe => watch mailbox for update
          # subscribe = true;
        };
        "Drafts" = {
          query = "tag:draft";
          # subscribe = true;
        };
        "Sent" = {
          # query="from:username@server.tld from:username2@server.tld";
          # include variations later ?
          query = "from:${secrets.accounts.mail.fastmail_perso.email}";
          # subscribe = true;
        };
        Trash = {
          # query="from:username@server.tld from:username2@server.tld";
          # include variations later ?
          query = "tag:killed";
          role = "Trash";
          # subscribe = true;
        };
      };
      # "INBOX" = {  query="tag:inbox and not tag:killed", subscribe = true }
      # "Drafts" = {  query="tag:draft", subscribe = true }
      # "Sent" = {  query="from:username@server.tld from:username2@server.tld", subscribe = true }

      settings = {

        # until https://git.meli-email.org/meli/meli/issues/700 gets fixed
        # manual_refresh = true;
        #  "systemctl start mujmap-fastmail"
        #   refresh_command = "just -g mail-sync";

        # could be generated from the module
        # manpage says:
        # send_mail String|SmtpServerConf       Command to pipe new mail to (exit code  must  be  0
        # send_mail = "msmtp --read-recipients --read-envelope-from";
        format = "notmuch"; # HM generates "jmap" by default
        # must hint at folder with .notmuch DB
        root_mailbox = config.accounts.email.maildirBasePath;

        #TODO
        # vcard_folder =

        # plain | threaded | compact | conversations
        listing.index_style = "compact";
        shortcuts.listing = {
          commands = [
            {
              command = [ "tag remove trash" ];
              shortcut = "D";
            }
            {
              command = [ "tag add trash" ];
              shortcut = "d";
            }
          ];

          # D =  "tag add trash";
          # { command = [ "tag add trash", "flag set trash" ], shortcut = "d" } ]
          # D =
        };

        # not liked
        # conf_override = true;

        notmuch_address_book_query = "--output=recipients --deduplicate=address date:6M..";
        # manual_refresh = false # defaults to false
        # TODO could be generated
        refresh_command = "systemctl start mujmap-fastmail";
        # extra_identities  =

        # server_password_command = getPasswordCommand "perso/fastmail_mc_jmap";
        # server_username = null;
        # server_url = null;
        # server_password_command = null;
      };
    };

    # folders.sent = "[Gmail]/Sent Mail";

    msmtp.enable = true;
    aerc.enable = true;
    notmuch = {
      enable = true;
      # fqdn = "fastmail.com";
    };
    mujmap = {
      enable = true;
      # session_url Mutually exclusive with `fqdn`.
      # fqdn = null;
      settings.fqdn = "fastmail.com";
      # TODO replace with pass
      # settings.password_command = "cat /home/teto/mujmap_password";
      # look at https://github.com/elizagamedev/mujmap/blob/main/mujmap.toml.example
      # for example
      # getPasswordCommand
      settings.username = secrets.accounts.mail.fastmail_perso.email;
      # settings.password_command = getPasswordCommand "perso/fastmail_mc_jmap";
      # ${pkgs.pass-teto}/bin/
      # ${pkgs.strace}/bin/strace -o /tmp/mujmap.log -f
      settings.password_command = "${pkgs.pass-perso}/bin/pass-perso show perso/fastmail_mc_jmap";
      settings.config_dir = mailDirBasePath;

      # settings.session_url = "https://api.fastmail.com/.well-known/jmap";
      # settings.session_url = "https://api.fastmail.com/jmap/session";
      # check example at https://github.com/elizagamedev/mujmap/blob/main/mujmap.toml.example
      # settings.timeout = 5
    };

    # described here https://www.fastmail.com/help/technical/servernamesandports.html
    # imap = { host = "imap.fastmail.com"; tls = my_tls; };
    # smtp = { host = "smtp.fastmail.com"; tls = my_tls; };
    # smtp.tls.useStartTls = false;
  };

  gmail = accountExtra // {
    gpg = gpgModule;
    astroid.enable = true;
    thunderbird.enable = true;

    # folders.drafts = "[Gmail]/Drafts";
    # folders.inbox = "Inbox";

    # Relative path of the inbox mail.
    folders.sent = "Sent";
    folders.trash = "Trash";

    # CopyArrivalDate
    # mbsync = mbsyncConfig // {
    #   remove = "both";
    #   # how to destroy on gmail ?
    #   # expunge = "both";
    #   # Exclude everything under the internal [Gmail] folder, except the interesting folders
    #   # Patterns * ![Gmail]* "[Gmail]/Sent Mail" "[Gmail]/Starred" "[Gmail]/All Mail"
    #   # "[Gmail]/Inbox"
    #   # patterns = ["* ![Gmail]*" "[Gmail]/Sent Mail" "[Gmail]/Starred" ];
    #   # to be able to create drafts ?
    #   create = "both";
    #   groups.personal = {
    #     channels = {
    #       inbox = {
    #         farPattern = "";
    #         nearPattern = "";
    #         extraConfig = {
    #           Create = "Both";
    #         };
    #       };
    #       sent = {
    #         # farPattern = config.accounts.email.accounts.gmail.folders.sent;
    #         farPattern = "[Gmail]/Sent Mail";
    #         nearPattern = "Sent";
    #         extraConfig = {
    #           Create = "Both";
    #         };
    #       };
    #       trash = {
    #         farPattern = config.accounts.email.accounts.gmail.folders.trash;
    #         # farPattern = "[Gmail]/Trash";
    #         nearPattern = "Trash";
    #         extraConfig = {
    #           Create = "Both";
    #         };
    #       };
    #       # starred = {
    #       #   farPattern = "[Gmail]/Starred";
    #       #   nearPattern = "Starred";
    #       # };
    #       # drafts = {
    #       #   farPattern = config.accounts.email.accounts.gmail.folders.drafts;
    #       #   nearPattern = "Drafts";
    #       # };
    #       # spam = {
    #       #   farPattern = config.accounts.email.accounts.gmail.folders.drafts;
    #       #   nearPattern = "Spam";
    #       # };
    #     };
    #   };
    #   extraConfig.account = {
    #     # PipelineDepth = 50;
    #     # AuthMechs = "LOGIN";
    #     # SSLType = "IMAPS";
    #     # SSLVersions = "TLSv1.2";
    #   };
    #   extraConfig.remote = {
    #     Account = "gmail";
    #   };
    #   extraConfig.local = {
    #     SubFolders = "Verbatim";
    #   };
    # };

    msmtp.enable = true;
    notmuch.enable = true;
    mujmap.enable = false;

    userName = secrets.accounts.mail.gmail_perso.address;
    realName = "Matt";
    address = secrets.accounts.mail.gmail_perso.address;
    flavor = "gmail.com";
    smtp.tls.useStartTls = true;

    passwordCommand = getPasswordCommand "perso/gmail";
  };

in
{
  # accounts.email = {
  maildirBasePath = mailDirBasePath;
  accounts = lib.optionalAttrs withSecrets {
    inherit
      gmail
      fastmail
      ;
  };
  # };

}
