" To debug mappings, type :verbose map <mapping>

" marker starts with " <section name> {{{ and finishes with  }}}
"set foldmethod=marker
set nocompatible               " be iMproved
"
" vim specific codes
if !has('nvim')
    " terminal codes are ignored by neovim
    " https://github.com/neovim/neovim/issues/2330
    set t_Co=256                        " use 256 colors
	scriptencoding utf-8
	" allow to use fancy caracters
	if &termencoding == ""
		let &termencoding = &encoding
	endif
	set encoding=utf-8
	setglobal fileencoding=utf-8
endif

source $XDG_CONFIG_HOME/nvim/init.vim
