
https://opensource.com/article/19/4/gpg-subkeys-ssh

A GPG key is actually a collection of keys. There is one primary key, which is typically used only for signing and certification. The suggested usage of GPG is to create a subkey for encryption. This subkey is a separate key that, for all intents and purposes, is signed by your primary key and transmitted at the same time. This practice allows you to revoke the encryption subkey on its own, such as if it becomes compromised, while keeping your primary key valid.

The important thing to realize is that a GPG key contains multiple keys. For backup and storage purposes, you can operate them as though they are one key, but when it is time to use a key, you can use them independently.
* gpg-agent

@begin
gpg-connect-agent updatestartuptty /bye

export DBUS_SESSION_BUS_ADDRESS=/dev/null
export PINENTRY_BINARY="/usr/bin/pinentry-tty"

* SSH_AUTH_SOCK

tells SSH tools where to find the agent’s Unix socket. With gpg-agent’s SSH support enabled, pointing this variable at its SSH socket makes ssh and ssh-add use gpg-agent:

  export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"

  This lets gpg-agent handle SSH authentication, including with a suitable authentication key on a smartcard or YubiKey.

* 
 gpg --export-ssh-key <key id> > .ssh/id_rsa.pub

* A TUI can help

since there is no completion

  nix shell nixpkgs#gpg-tui

  is really helpful

You can always use a key ID instead of a user ID. For example, for encrypting a message to my newer key:
gpg --encrypt --recipient A4FF2279


--armor just creates ascii text instead of raw binary data. convenient for emails etc

Si tu as operation annulée au moment d'entrer ton mot de passe, c'est que le
pinentry foire. Tu peux installer pinentry-curses (apparemment utilisée par
		défaut si t'as:
export GPG_TTY=$(tty); unset DISPLAY 
dans ton terminal auparavant.

gpgconf --check-programs
gpg --list-keys
gpg --list-secret-keys

To
https://stackoverflow.com/questions/28321712/gpg-decryption-fails-with-no-secret-key-error

gpg-agent --debug-all --no-detach --log-file

To kill the agent 
gpgconf --kill gpg-agent

gpg-agent.conf contains:


# To trust a key:
gpg --edit-key peerKey.asc
gpg > trust

* inspect a gpg secret 

gpg --list-packets ~/.password-store/6play.fr.gpg
