#+title: zsh tips 

* merge histories

To load history from file:
builtin fc -R -I "$hist_file_1"

SHARE_HISTORY

Flush history / HIST_FILE
builtin fc -W "$hist_file_merged"

zsh --help shows different commands:


https://unix.stackexchange.com/questions/74184/how-to-save-current-command-on-zsh

push-line mapping

* bypass local config
  zsh -f <=> --no-rcs => disable local config
  -d disables global config
  zsh -lxv to debug

* test

"zle -N" Create a user-defined widget.  If there is already a widget with the specified name, it is overwritten

zle -al lists all registered widgets

echo $widgets[accept-line]

you can run zsh -f. If you want to skip system configuration files but run the per-user files, run zsh -d.

zsh/zleparameter

https://zsh.sourceforge.io/Doc/Release/User-Contributions.html#Manipulating-Hook-Functions


* List hooks

  zshaddhistory

`source ~/.config/zsh/zhooks.plugin.zsh` then run `zhooks`
`add-zsh-hook -L [HOOK]`

add-zsh-hook -d preexec [existing_function_name]


To remove registered preexec function
add-zsh-hook -D preexec set_term_title

* completion

zstyle -L 
https://zsh.sourceforge.io/Doc/Release/Completion-System.html
When compinit is run, it searches all such files accessible via fpath/FPATH and reads the first line of each of them. This line should contain one of the tags described below. Files whose first line does not start with one of these tags are not considered to be part of the completion system and will not be treated specially.

#compdef simwork.core-webservice.local =

Might be 
