{
  lib,
  secretsFolder,
  flakeSelf,
}:
final: prev:
let
  # see https://github.com/NixOS/nixpkgs/issues/29605#issuecomment-332474682
  # In lib/sources.nix we have "cleanSource = builtins.filterSource cleanSourceFilter;"
  # TODO builtins.filterSource (p: t: lib.cleanSourceFilter p t && baseNameOf p != "build")
  filter-cmake = builtins.filterSource (
    p: t: prev.lib.cleanSourceFilter p t && baseNameOf p != "build"
  );

  notify-send = "${final.libnotify}/bin/notify-send";

in
{
  tetos = {
    # TODO pass icon
    muteAudio = prev.writeShellScript "mute-volume" ''

      ${final.wireplumber}/bin/wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle; ${notify-send} --icon=speaker_no_sound -e -h boolean:audio-toggle:1 -h string:synchronous:audio-volume -u low 'Toggling audio';
    '';

    # -f --image ~/.config/wallpapers/snow_woods.jpg"
    swaylockCmd = prev.writeShellScript "lock-screen" ''
      ${final.swaylock-effects}/bin/swaylock
    '';
  };

  meli-git = final.meli.overrideAttrs (drv: rec {
    name = "meli-${version}";
    version = "g${flakeSelf.inputs.meli-src.shortRev}";
    src = flakeSelf.inputs.meli-src;

    cargoPatches = [ ];
    useFetchCargoVendor = true;

    cargoDeps = final.rustPlatform.fetchCargoVendor {
      inherit src;
      hash = "sha256-OyOLAw3HzXY85Jwolh4Wqjmm6au6wRwGq5WkicOt5eg=";
    };

    checkFlags = drv.checkFlags ++ [
      "--skip=test_imap_watch"
    ];
  });

  pass-import-high-password-length = final.passExtensions.pass-import.overrideAttrs ({

    src = final.fetchFromGitHub {
      owner = "teto";
      repo = "pass-import";
      rev = "d903431e73e88406c32e58196a468662bca55055";
      hash = "sha256-95BJ5l0JNem8zHF6aJwA7TijORGOX2DK5rIw5DGJe+k=";
    };

  });

  backblaze-b2-tetos = final.backblaze-b2.override { execName = "b2"; };

  # replaced by native yazi ?
  # rsync-yazi = myPkgs.yaziPlugins.mkYaziPlugin {
  #   pname = "rsync.yazi";
  #   version = "g${self.inputs.rsync-yazi-plugin.shortRev}";
  #   src = self.inputs.rsync-yazi-plugin;
  # };

  buildFirefoxXpiAddon =
    {
      stdenv ? final.stdenv,
      fetchurl ? final.fetchurl,
      pname,
      version,
      addonId,
      url,
      sha256,
      meta,
      ...
    }:
    stdenv.mkDerivation {
      name = "${pname}-${version}";

      inherit meta;

      src = fetchurl { inherit url sha256; };

      preferLocalBuild = true;
      allowSubstitutes = true;

      passthru = {
        inherit addonId;
      };

      buildCommand = ''
        dst="$out/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}"
        mkdir -p "$dst"
        install -v -m644 "$src" "$dst/${addonId}.xpi"
      '';
    };

  firefox-addons = import ./firefox/generated.nix {
    # inherit (lib.firefox)       buildFirefoxXpiAddon;
    inherit lib;
    inherit (final)
      buildFirefoxXpiAddon
      fetchurl
      stdenv
      ;
  };

  immich-no-ad = prev.immich.overrideAttrs ({
    # # overrides
    # hideBuyButton ? false,
    postPatch = ''
      substituteInPlace src/lib/components/shared-components/side-bar/purchase-info.svelte \
        --replace-fail "showBuyButton = getButtonVisibility()" "showBuyButton = false"
    '';
  });

  mujmap-unstable = flakeSelf.inputs.mujmap.packages.x86_64-linux.mujmap;

  # # cant put in autogenerated overlays because it needs extra arg "secretsFolder"
  # pass-perso = (final.pass.override ( {
  #     wrapperArgs = "--set PASSWORD_STORE_DIR ${secretsFolder}/password-store-perso"
  #     ;
  #   })).overrideAttrs({ doInstallCheck = false ; });
  #

  # in the source code we have:
  # PREFIX="${PASSWORD_STORE_DIR:-$HOME/.password-store}"
  # EXTENSIONS="${PASSWORD_STORE_EXTENSIONS_DIR:-$PREFIX/.extensions}"
  pass-perso = final.writeShellApplication {
    name = "pass-perso";
    runtimeInputs = [
      # final.pass-teto
    ];
    text = ''
      export PASSWORD_STORE_DIR="${secretsFolder}/password-store-perso"
      ${final.pass-teto}/bin/pass $@
    '';
    checkPhase = ":";
  };

  neomutt-dev = prev.lib.warn "neomutt override" (
    prev.neomutt.overrideAttrs ({
      src = flakeSelf.inputs.neomutt-src;
    })
  );

  # see https://github.com/NixOS/nixpkgs/pull/257760
  # ollamagpu = final.ollama.override { llama-cpp = final.llama-cpp-matt; };

  protocol-local = prev.protocol.overrideAttrs (oldAttrs: {
    src = builtins.fetchGit { url = "https://github.com/teto/protocol"; };
  });

  termscp-matt = prev.termscp.overrideAttrs (oa: {
    cargoBuildFlags = "--no-default-features";
  });

  # this exists in ml-tests, let's upstream some of the changes first
  # jupyter4ihaskell = myPkgs.jupyter-teto;
  # jupyter-teto = python3.withPackages(ps: [
  #  ps.notebook
  #  ps.jupyter-client
  # ]);

  # # TODO get lua interpreter to select the good lua packages
  # nvimLua = config.programs.neovim.finalPackage.passthru.unwrapped.lua;

  # luajit = prev.luajit.override {
  #   packageOverrides = self.inputs.rikai-nvim.overlays.luaOverlay;
  # };
  #
  # lua5_1 = prev.lua5_1.override {
  #   packageOverrides = self.inputs.rikai-nvim.overlays.luaOverlay;
  # };

  # overrideAttrs (oldAttrs: {
  #   src = prev.fetchFromGitHub {
  #     owner = "flameshot-org";
  #     repo = "flameshot";
  #     rev = "3d21e4967b68e9ce80fb2238857aa1bf12c7b905";
  #     sha256 = "sha256-OLRtF/yjHDN+sIbgilBZ6sBZ3FO6K533kFC1L2peugc=";
  #   };
  #   cmakeFlags = [
  #     "-DUSE_WAYLAND_CLIPBOARD=1"
  #     "-DUSE_WAYLAND_GRIM=1"
  #   ];
  #   buildInputs = oldAttrs.buildInputs ++ [ final.libsForQt5.kguiaddons ];
  # });

  # xdg-utils = prev.xdg-utils.overrideAttrs(oa: {
  #   pname = "xdg-utils-custom";
  #   name = "xdg-utils-custom-matt";
  #   # version = "matt";
  #   patches = [
  #     ./patches/xdg_utils_symlink.diff
  #   ];
  # });

}
