#!/bin/sh
# --input implies --batch
# look at notmuch search terms attachment:
notmuch tag --input="$XDG_CONFIG_HOME/notmuch/ietf"
notmuch tag --input="$XDG_CONFIG_HOME/notmuch/foss"
#notmuch tag --batch --input="$XDG_CONFIG_HOME/notmuch/security"
