#!/bin/sh
set -ex

EVENT="$2"

env > /tmp/if_down_env

if [ "$IFACE" = lo -o "$MODE" != stop ]; then
        exit 0
fi

if [ "$EVENT" != "down" ]; then
	logger "exit $EVENT != down"
fi

ip rule del table "$DEVICE_IFACE"
ip route flush table "$DEVICE_IFACE"

