# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  # does not work anymore with flakes
  # imports =
  #   [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
  #   ];

  # replace it in the flake with
  # modules = [ pkgs.nixosModules.notDetected ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # to remove "TSC_DEADLINE disabled due to Errata;
  # please update microcode to version: 0x22"
  hardware.cpu.intel.updateMicrocode = true;
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/443ce6b0-e43e-43e6-9d10-c0c6293ccf66";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/ebbfc6ca-a0f0-4b8b-ac1e-7a2b4390d72c"; }
    ];

  fileSystems."/mnt/ext" =
    { device = "/dev/disk/by-uuid/d118729e-bc3d-4e02-bf6b-f0cb54fef2a1";
      fsType = "ext4";
      # "exec"
      # user disables exec
      options = [ "defaults" "user" "exec" "nofail"];
    };

  fileSystems."/mnt/ntfs" =
    {
      device = "/dev/sda2";
      fsType = "ntfs";
      # see https://nixos.wiki/wiki/NTFS
      options = [ "rw" "uid=teto""nofail"  ];
    # options = [ "user", ];
    };



  nix.maxJobs = lib.mkDefault 4;
  # Often used values: "ondemand", "powersave", "performance"
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
