{
  config,
  secrets,
  lib,
  withSecrets,
  ...
}:
{
  networking = {
    useNetworkd = true;
    useDHCP = false;
    hostName = "router"; # or router
    domain = "router.local";

    # networking.dhcpcd.enable = true;
    usePredictableInterfaceNames = true;
    # networking.firewall.interfaces.enp1s0.allowedTCPPorts = [ 4949 ];

    wireguard.interfaces = {
      wg0 = lib.mkWireguardPeer {

        id = 4;
        # TODO upload one
        privateKeyFile = "/home/teto/router-wg.key";
      };
    };

    firewall = {
      enable = false;
      interfaces.br0.allowedTCPPorts = [ 53 ];
      interfaces.br0.allowedUDPPorts = [ 53 ];

      # if home-assistant enabled, open
      # 8123
    };

    #   # address of the livebox
    #   defaultGateway = { address = "192.168.1.1"; interface = "wlp5s0"; };
    #  interfaces.enp1s0 = {
    #     useDHCP = true;
    #     # ipv4.addresses = [
    #     # { address = "192.168.1.127"; prefixLength = 24; }
    #     # ];
    #   };

    #   interfaces.wlp5s0 = {
    #     useDHCP = true;
    #     # ipv4.addresses = [
    #     # { address = "192.168.1.127"; prefixLength = 24; }
    #     # ];
    #   };

    #   interfaces.br0 = {
    #     ipv4.addresses = [
    #       bridgeNetwork
    #     ];
    #   };

    #   bridges.br0 = {
    #     interfaces = [ "enp2s0" "enp3s0" "enp4s0" ];
    #   };

    #   nat.enable = true;
    #   nat.externalInterface = externalInterface;
    #   nat.internalInterfaces = [ "br0" ];

    wireless = {
      enable = true; # Whether to enable wpa_supplicant., we use iwd here

      # Allow users of the ‘wpa_supplicant’ group to control wpa_supplicant through wpa_gui or wpa_cli. This is useful for laptop users that switch networks a lot and don’t want to depend on a large package such as NetworkManager just to pick nearby access points.
      # see https://github.com/NixOS/nixpkgs/issues/370938
      userControlled = true;

      #          Whether to allow configuring networks “imperatively” (e.g. via ‘wpa_supplicant_gui’) and declaratively via networking.wireless.networks[1].
      # his makes wpa_supplicant load /etc/wpa_supplicant.conf in addition to the configuration generated by NixOS.
      # allowAuxiliaryImperativeNetworks = false;

      # content of wireless.conf
      # psk_home=mypassword
      # psk_other=6a381cea59c7a2d6b30736ba0e6f397f7564a044bcdb7a327a1d16a1ed91b327
      # pass_work=myworkpassword
      #
      # TODO create manually
      secretsFile = "/etc/wireless.conf";

      # secretsFile = "/home/teto/wireless.conf";
      scanOnLowSignal = false; # consume less energy and we dont roam anyway

      # checkout man iwd.config
      # ignores networks apparently :s
      iwd = {
        enable = false;
        # https://iwd.wiki.kernel.org/networkconfigurationsettings
        settings = {
          Settings = {
            AutoConnect = true;
            AlwaysRandomizeAddress = false;
          };
          Network = {
            EnableIPv6 = false;
          };

          Rank = {
            # supposed to be the default
            BandModifier5Ghz = 1;
          };
          Scan = {

            DisablePeriodicScan = true;
            # supp

          };

          # DriverQuirks = {
          #
          # };
          # IpV4
          # APAddressPool
          # Security = {
          #   Passphrase = secrets.router.password;
          # };

          # psk = secrets.router.password;
        };
      };

      networks = {
        "${secrets.wifiNetworks.home.ssid}" = {
          pskRaw = "ext:psk_home";
          # echelon = {                   # safe version of the above: read PSK from the
          #   pskRaw = "ext:psk_echelon"; # variable psk_echelon, defined in secretsFile,
          # };                            # this won't leak into /nix/store

          # pskRaw
          # appended to wpa_supplicant.conf
          # freq_list=5180 5190 5200 5210 5220 5230 5240 5250 5260 5270 5280
          #

          #            freq_list=5180 5190 5200 5210 5220 5230 5240 5250 5260 5270 5280

          # extraConfig = ''
          #  bssid_whitelist=04:E3:1A:6A:CF:05
          #  '';
        };
      };
    };
  };

}
