golden-test:
  nix run  .#fastbuild.simwork.core-webservice.golden-test

local:
  nix run  .#fastbuild.simwork.core-webservice.local

platform:
  nix run  .#fastbuild.simwork.core-webservice.platform

sscwl:
  nix run .#simwork.core-webservice.local -- --bypass-manifest-check -vv
