
-- https://github.com/nvim-neotest/neotest#usage
-- require("neotest").run.run()
-- require("neotest").setup({
--   adapters = {
--    require('neotest-haskell') {
-- 	 -- Default: Use stack if possible and then try cabal
-- 	 build_tools = {
-- 	  'nix'
-- 	  -- 'stack', 'cabal'
-- 	 },
-- 	 -- Default: Check for tasty first and then try hspec
-- 	 frameworks = {
-- 	   -- 'tasty',
-- 	   'hspec',
-- 	   -- 'sydtest'
-- 	 },
--    },
-- 	-- require("neotest-plenary"),
-- 	-- require("neotest-vim-test")({
-- 	--   ignore_file_types = { "python", "vim", "lua" },
-- 	-- }),
--   },
-- })
