# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #BCBABE

background #2E2A31
foreground #BCBABE

color0 #2E2A31
color1 #D8137F
color2 #17AD98
color3 #DC8A0E
color4 #796AF5
color5 #BB60EA
color6 #149BDA
color7 #BCBABE
color8 #838085
color9 #D8137F
color10 #17AD98
color11 #DC8A0E
color12 #796AF5
color13 #BB60EA
color14 #149BDA
color15 #F5F4F7

mark1_foreground #109ADA
mark2_foreground #A995BE
mark3_foreground #109ADA
