# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #4C4F69

background #EFF1F5
foreground #4C4F69

color0 #5C5F77
color1 #D20F39
color2 #40A02B
color3 #DF8E1D
color4 #1E66F5
color5 #EA76CB
color6 #179299
color7 #ACB0BE
color8 #6C6F85
color9 #D20F39
color10 #40A02B
color11 #DF8E1D
color12 #1E66F5
color13 #EA76CB
color14 #179299
color15 #BCC0CC

mark1_foreground #129299
mark2_foreground #8A95BE
mark3_foreground #129299
