# The kitty terminal template for wallust
# Add to wallust config: kitty = { src='kitty.conf', dst='~/.config/kitty/colors.conf'}
# And add to kitty config: include colors.conf

cursor #D0D0D0

background #262626
foreground #D0D0D0

color0 #1C1C1C
color1 #D68686
color2 #AED686
color3 #D7AF87
color4 #86AED6
color5 #D6AED6
color6 #8ADBB4
color7 #D0D0D0
color8 #1C1C1C
color9 #D68686
color10 #AED686
color11 #E4C9AF
color12 #86AED6
color13 #D6AED6
color14 #B1E7DD
color15 #EFEFEF

mark1_foreground #6EDBA7
mark2_foreground #D0A6A6
mark3_foreground #6EDBA7
