## Setting up an account for an already existing notmuch database
# [accounts.notmuch]
# root_mailbox = "/home/teto/maildir" # where .notmuch/ directory is located
# send_mail = 'msmtp --read-recipients --read-envelope-from'
# # where to find notmuch
# library_file_path = "/nix/store/lw4hjgnypk3lbvlflc2v4lygxpw7pq9n-notmuch-0.38.3/lib/libnotmuch.so"
# format = "notmuch"
# identity="matthieucoudron@fastmail.com"
# display_name = "Matthieu coudron"
# manual_refresh = false # defaults to false
# refresh_command = "just -g mail-fetch"
# listing.index_style = "compact"
# listing.index_style = ""
[accounts.notmuch.listing]
index_style = "compact"

  # notmuch mailboxes are virtual, they are defined by their alias and the notmuch query that corresponds to their content.
  [accounts.notmuch.mailboxes]
  "INBOX" = {  query="tag:inbox and not tag:killed", subscribe = true }
  "Drafts" = {  query="tag:draft", subscribe = true }
  "Sent" = {  query="from:username@server.tld from:username2@server.tld", subscribe = true }


[log]
# TRACE
# careful
maximum_level = "DEBUG"

[terminal]
use_color = true
window_title = "Meli"
use_mouse = true
# progress_spinner_sequence = 0
progress_spinner_sequence = { frames = [] }
#theme = "dark" # or "light"

# [notifications]
# script = "notify-send"

#[pager]
#filter = "COLUMNS=72 /usr/local/bin/pygmentize -l email"
#pager_context = 0 # default, optional
#headers_sticky = true # default, optional

[pager]
# filter = "COLUMNS=72 /usr/local/bin/pygmentize -l email"
html_filter = "w3m -I utf-8 -T text/html"

#[notifications]
#script = "notify-send"
#xbiff_file_path = "path" # for use with xbiff(1)
#play_sound = true # default, optional
#sound_file = "path" # optional

###shortcuts
[shortcuts.general]
next_tab = ']'

# listing-compact
[shortcuts.listing]
# scroll_up = "up"
# scroll_down = "down"
focus_left = "left"
focus_right = "right"

# [shortcuts.composing]
# edit_mail = 'e'

#
##Thread view defaults:
#[shortcuts.compact-listing]
#exit_thread = 'i'
#
#[shortcuts.contact-list]
#create_contact = 'c'
#edit_contact = 'e'
#
##Mail listing defaults
#[shortcuts.listing]
#prev_page = "PageUp"
#next_page = "PageDown"
#prev_mailbox = 'K'
#next_mailbox = 'J'
#prev_account = 'l'
#next_account = 'h'
#new_mail = 'm'
#set_seen = 'n'
#
##Pager defaults
#
#[shortcuts.pager]
#scroll_up = 'k'
#scroll_down = 'j'
#page_up = "PageUp"
#page_down = "PageDown"

# [composing]
# #required for sending e-mail
# editor_command = 'nvim +/^$' # optional, by default $EDITOR is used.

#[pgp]
#auto_sign = false # always sign sent messages
#auto_verify_signatures = true # always verify signatures when reading signed e-mails
#gpg_binary = "/usr/bin/gpg2" #optional
