## Setting up an account for an already existing notmuch database


[tags]
# valid inputs: #HHHHHH, #ABC -> #AABBCC, XTERM_NAME, 0-255 byte
colors = { signed="#Ff6600", replied="DeepSkyBlue4", draft="#f00" }
# ignore_tags

# display_name =
# extra_identities 
# refresh_command = "just -g mail-fetch"

 
[listing]
# datetime_fmt String                   (optional)  Datetime  formatting passed verbatim to
#                                       strftime(3).  (%Y-%m-%d %T)
recent_dates = true
index_style = "compact"


[log]
# TRACE
# careful
maximum_level = "TRACE"

# mailboxes
# "Archives" = {  query="tag:archived", subscribe = true }
# "Archives/2019" = {  query="tag:archived date:01-2019..12-2019", parent="Archives", subscribe = true }


[terminal]
use_color = true
# would be cool to display number of unread but not possible
window_title = "My emails"
use_mouse = true
# progress_spinner_sequence = 0
# progress_spinner_sequence = { frames = [] }
theme = "nord" # or "light"
force_text_presentation = true
# use in 'save-attachment' command
file_picker_command = "vifm --choose-dir - --delimiter ''"

[notifications]
# with title as 1st arg and body as 2nd
# https://meli-email.org/documentation.html#meli.conf.5_new_mail_script
# custom script in bin/
# enable = "system_only"
script = "meli-notif"
#xbiff_file_path = "path" # for use with xbiff(1)
#play_sound = true # default, optional
#sound_file = "path" # optional

#[pager]
#filter = "COLUMNS=72 /usr/local/bin/pygmentize -l email"
#pager_context = 0 # default, optional
#headers_sticky = true # default, optional

[pager]
# filter = "COLUMNS=72 /usr/local/bin/pygmentize -l email"
html_filter = "w3m -I utf-8 -T text/html"
sticky_headers = true
# String                         (optional) A command to pipe mail output through for viewing in pager.
# filter 
named_filters = { diff = "pygmentize -l diff -f 256", par = "par 72" }
# url_launcher =  xdg-open by default


###shortcuts
[shortcuts.general]
next_tab = ']'
quit = 'Q'
commands = [
 { command = [ "tag remove trash"  ], shortcut = "D" },
   { command = [ "tag add trash"  ], shortcut = "d"}
]

# listing.sort = ["date", "asc"]


# listing-compact
[shortcuts.listing]
# # scroll_up = "up"
# # scroll_down = "down"
# focus_left = "left"
# focus_right = "right"
focus_right = "l"
focus_left = "h"
exit_entry = "q"



[shortcuts.envelope_view]
toggle_expand_headers = "H"

# [shortcuts.composing]
# edit_mail = 'e'

#
##Thread view defaults:
#[shortcuts.compact-listing]
#exit_thread = 'i'
#
#[shortcuts.contact-list]
#create_contact = 'c'
#edit_contact = 'e'
#
##Mail listing defaults
#[shortcuts.listing]
#prev_page = "PageUp"
#next_page = "PageDown"
#prev_mailbox = 'K'
#next_mailbox = 'J'
#prev_account = 'l'
#next_account = 'h'
#new_mail = 'm'
#set_seen = 'n'
#
##Pager defaults
#
#[shortcuts.pager]
#scroll_up = 'k'
#scroll_down = 'j'
#page_up = "PageUp"
#page_down = "PageDown"

# [composing]
# #required for sending e-mail
# editor_command = 'nvim +/^$' # optional, by default $EDITOR is used.

#[pgp]
#auto_sign = false # always sign sent messages
#auto_verify_signatures = true # always verify signatures when reading signed e-mails
#gpg_binary = "/usr/bin/gpg2" #optional
