## Setting up an account for an already existing notmuch database

# display_name =
# extra_identities 
# refresh_command = "just -g mail-fetch"

# listing.index_style = "compact"
# listing.index_style = ""
# [accounts.notmuch.listing]
# index_style = "compact"

# [accounts.fastmail.mailboxes]
# "INBOX" = {  query="tag:inbox and not tag:killed", subscribe = true }
# "Drafts" = {  query="tag:draft", subscribe = true }
# "Sent" = {  query="from:username@server.tld from:username2@server.tld", subscribe = true }


[log]
# TRACE
# careful
maximum_level = "TRACE"

# mailboxes
# "Archives" = {  query="tag:archived", subscribe = true }
# "Archives/2019" = {  query="tag:archived date:01-2019..12-2019", parent="Archives", subscribe = true }


[terminal]
use_color = true
# would be cool to display number of unread but not possible
window_title = "My emails"
use_mouse = true
# progress_spinner_sequence = 0
# progress_spinner_sequence = { frames = [] }
theme = "nord" # or "light"

[notifications]
# with title as 1st arg and body as 2nd
# https://meli-email.org/documentation.html#meli.conf.5_new_mail_script
# custom script in bin/
script = "meli-notif"
#script = "notify-send"
#xbiff_file_path = "path" # for use with xbiff(1)
#play_sound = true # default, optional
#sound_file = "path" # optional

#[pager]
#filter = "COLUMNS=72 /usr/local/bin/pygmentize -l email"
#pager_context = 0 # default, optional
#headers_sticky = true # default, optional

[pager]
# filter = "COLUMNS=72 /usr/local/bin/pygmentize -l email"
html_filter = "w3m -I utf-8 -T text/html"

###shortcuts
[shortcuts.general]
next_tab = ']'
quit = 'Q'
commands = [
 { command = [ "tag remove trash"  ], shortcut = "D" },
   { command = [ "tag add trash"  ], shortcut = "d"}
]



# listing-compact
# [shortcuts.listing]
# # scroll_up = "up"
# # scroll_down = "down"
# focus_left = "left"
# focus_right = "right"
# exit_entry = "q"

# [shortcuts.composing]
# edit_mail = 'e'

#
##Thread view defaults:
#[shortcuts.compact-listing]
#exit_thread = 'i'
#
#[shortcuts.contact-list]
#create_contact = 'c'
#edit_contact = 'e'
#
##Mail listing defaults
#[shortcuts.listing]
#prev_page = "PageUp"
#next_page = "PageDown"
#prev_mailbox = 'K'
#next_mailbox = 'J'
#prev_account = 'l'
#next_account = 'h'
#new_mail = 'm'
#set_seen = 'n'
#
##Pager defaults
#
#[shortcuts.pager]
#scroll_up = 'k'
#scroll_down = 'j'
#page_up = "PageUp"
#page_down = "PageDown"

# [composing]
# #required for sending e-mail
# editor_command = 'nvim +/^$' # optional, by default $EDITOR is used.

#[pgp]
#auto_sign = false # always sign sent messages
#auto_verify_signatures = true # always verify signatures when reading signed e-mails
#gpg_binary = "/usr/bin/gpg2" #optional
