# use it with:
# ln -sf $HOME/home/nova/justfile justfile.local
tc:
  nix run  .#typecheck

deps:
  nix run  .#mk_deps_file

unit:
  nix run  .#simwork.core-webservice.unit

golden-test:
  nix run  .#fastbuild.simwork.core-webservice.golden-test

local:
  nix run  .#fastbuild.simwork.core-webservice.local -- --bypass-manifest-check

platform:
  nix run  .#fastbuild.simwork.core-webservice.platform

repl:
  # TODO:
  # autoload System.Environment
  # setEnv "PORCUPINE_ARGS" "--bypass-manifest-check -vv"
  # --ghci-args 
  # --ghci-script
  nix run  .#simwork.core-webservice.platform._repl 
