# use it with:
# ln -sf $HOME/home/nova/justfile justfile.local

# typecheck
tc:
  nix run  .#typecheck

# regenerate nix deps file 
deps:
  nix run  .#mk_deps_file

# run cws golden tests
golden:
  nix run  .#simwork.core-webservice.unit -- "Golden "

# reset 
golden-reset:
  nix run  .#simwork.core-webservice.unit -- "Golden " --golden-reset

# run core tests
unit:
  nix run  .#simwork.core-webservice.unit

# reset the openapi doc
openapi-reset:
  nix run  .#simwork.core-webservice.unit -- "openapi" --golden-reset

golden-test:
  nix run  .#fastbuild.simwork.core-webservice.golden-test

local:
  nix run  .#fastbuild.simwork.core-webservice.local    -- --bypass-manifest-check --migrate-sql-tables

platform:
  nix run  .#fastbuild.simwork.core-webservice.platform -- --bypass-manifest-check --migrate-sql-tables

sscwl:
  nix run .#simwork.core-webservice.local -- --bypass-manifest-check -vv

repl-cw:
  # System.Environment.setEnv "PORCUPINE_ARGS" "--bypass-manifest-check -vv"
  # --ghci-args 
  # --ghci-script
  # :set args "--bypass-manifest-check"
  nix run  .#simwork.core-webservice.platform._repl 
 
# -ghci-script can be set several times
# https://downloads.haskell.org/ghc/latest/docs/users_guide/ghci.html#ghc-flag-ghci-script
repl:
  # sydTestWith Test.Syd.OptParse.defaultSettings spec
  # ghci> import Test.Syd.OptParse 
  # ghci> s = settings { settingFilters = [ "monolix" ] }
  nix run  .#repl -- -Wno-x-vpop-patient-table -Wno-x-pre-v2-routes  -ghci-script {{parent_directory(canonicalize(source_file()))}}/ghci-script-core-ws.txt
  # cree un pb ?
  # -ghci-args ":l CoreWebserviceSpec"
