#!/bin/sh
# A script for setting up routing tables for MPTCP
# see http://multipath-tcp.org/pmwiki.php/Users/ConfigureRouting
# can check with (ins)[root@client:~]# journalctl -b -u NetworkManager-dispatcher.service
set -ex

RT_TABLE=/etc/iproute2/rt_tables

if [ "$DEVICE_IFACE" = "lo" ]; then
	echo "do nothing for localhost"
	exit 0
elif [ -z "$DEVICE_IFACE" ]; then
	echo "Ignoring empty interface"
	exit 0
fi

# egrep -c "^([[:digit:]]*)([[:space:]]*)virbr1" test.txt
# $(grep -c "$DEVICE_IFACE" "$RT_TABLE")
# res=$(grep -c "^[[:digit:]]*[[:space:]]\+$DEVICE_IFACE" "$RT_TABLE")
set +e
res=$(ip route show table "$DEVICE_IFACE")
retcode=$?

set -e

if [ $retcode -ne 0 ]; then
	echo "$PREFIX: Adding new routing table $DEVICE_IFACE"
	NUM=$(wc -l < "$RT_TABLE")
	echo -e "\n$NUM  $DEVICE_IFACE" >> "$RT_TABLE"
	# cat "$RT_TABLE"
fi

if [ -n "$DHCP4_IP_ADDRESS" ]; then
	SUBNET=`echo $IP4_ADDRESS_0 | cut -d \   -f 1 | cut -d / -f 2`
	ip route add to "$DHCP4_NETWORK_NUMBER/$SUBNET" dev "$DEVICE_IFACE" scope link table "$DEVICE_IFACE"
	ip route add default via $DHCP4_ROUTERS dev "$DEVICE_IFACE" table "$DEVICE_IFACE"
	ip rule add from "$DHCP4_IP_ADDRESS" table "$DEVICE_IFACE"
else
	# PPP-interface
	IPADDR=`echo $IP4_ADDRESS_0 | cut -d \   -f 1 | cut -d / -f 1`

	# if gateway is set
	if [ ! -z "$IP4_GATEWAY" ]; then
		ip route add default via "$IP4_GATEWAY" dev "$DEVICE_IFACE" table "$DEVICE_IFACE"
	else
		ip route add default dev "$DEVICE_IP_IFACE" scope link table "$DEVICE_IFACE"
	fi

	ip rule add from "$IPADDR" table "$DEVICE_IFACE"
fi

