[manager]

# run will become run soon

append_keymap = [
 	{ on = [ "<PageUp>" ], run = "arrow -15" },
	{ on = [ "<PageDown>" ], run = "arrow 15" },

	# compress zip files
	{ on = [ "c", "z" ], run = """
		shell 'printf "Your Name:"; read name; zip "$name.zip" "$@"' --block --confirm
	""" },
	# decompress zip files
	{ on = [ "z", "u" ],         run = "shell unzip $@", desc = "Unzip file" },

	{ on = [ "/" ], run = "find" },

	{ on = [ "<Esc>" ], run = "escape"  },
	{ on = [ "q" ], run = "quit" },
	{ on = [ "<C-q>" ], run = "close" },
	{ on = [ "<Esc>" ], run = "escape",  desc = "Exit visual mode, clear selected, or cancel search" },
	{ on = [ "q" ],     run = "quit",    desc = "Exit the process" },
	{ on = [ "<C-q>" ], run = "close",   desc = "Close the current tab, or quit if it is last tab" },
	{ on = [ "<C-z>" ], run = "suspend", desc = "Suspend the process" },

	# Navigation
	{ on = [ "k" ], run = "arrow -1" },
	{ on = [ "j" ], run = "arrow 1" },

	{ on = [ "K" ], run = "arrow -5" },
	{ on = [ "J" ], run = "arrow 5" },

	{ on = [ "h" ], run = "leave" },
	{ on = [ "l" ], run = "enter" },

	{ on = [ "H" ], run = "back" },
	{ on = [ "L" ], run = "forward" },

	{ on = [ "<Up>" ], run = "arrow -1" },
	{ on = [ "<Down>" ], run = "arrow 1" },
	{ on = [ "<Left>" ], run = "leave" },
	{ on = [ "<Right>" ], run = "enter" },

	# Selection
	{ on = [ "<Space>" ], run = [ "select --state=none", "arrow 1" ] },
	{ on = [ "v" ], run = "visual_mode" },
	{ on = [ "V" ], run = "visual_mode --unset" },
	{ on = [ "<C-a>" ], run = "select_all --state=true" },
	{ on = [ "<C-r>" ], run = "select_all --state=none" },

	# Operation
	{ on = [ "o" ], run = "open" },
	{ on = [ "O" ], run = "open --interactive" },
	{ on = [ "<Enter>" ], run = "open" },
	{ on = [ "<C-Enter>" ], run = "open --interactive" },  # It's cool if you're using a terminal that supports CSI u
	{ on = [ "y" ], run = "yank" },
	{ on = [ "x" ], run = "yank --cut" },
	{ on = [ "p" ], run = "paste" },
	{ on = [ "P" ], run = "paste --force" },
	{ on = [ "k" ], run = "paste --follow" },
	{ on = [ "K" ], run = "paste --follow --force" },
	{ on = [ "d" ], run = "remove" },
	{ on = [ "D" ], run = "remove --permanently --force" },
	{ on = [ "a" ], run = "create" },
	{ on = [ "r" ], run = "rename" },
	{ on = [ ";" ], run = "shell" },
	{ on = [ ":" ], run = "shell --block" },
	{ on = [ "." ], run = "hidden toggle" },
	{ on = [ "s" ], run = "search fd" },
	{ on = [ "S" ], run = "search rg" },
	{ on = [ "<C-s>" ], run = "search none" },
	{ on = [ "z" ], run = "jump zoxide" },
	{ on = [ "Z" ], run = "jump fzf" },

	# Copy
	{ on = [ "c", "c" ], run = "copy path" },
	{ on = [ "c", "d" ], run = "copy dirname" },
	{ on = [ "c", "f" ], run = "copy filename" },
	{ on = [ "c", "n" ], run = "copy name_without_ext" },

	# Sorting
	{ on = [ ",", "a" ], run = "sort alphabetical" },
	{ on = [ ",", "A" ], run = "sort alphabetical --reverse" },
	{ on = [ ",", "c" ], run = "sort created --reverse" },
	{ on = [ ",", "C" ], run = "sort created" },
	{ on = [ ",", "m" ], run = "sort modified --reverse" },
	{ on = [ ",", "M" ], run = "sort modified" },
	{ on = [ ",", "s" ], run = "sort size --reverse" },
	{ on = [ ",", "S" ], run = "sort size" },

	# Tabs
	{ on = [ "t" ], run = "tab_create --current" },

	{ on = [ "1" ], run = "tab_switch 0" },
	{ on = [ "2" ], run = "tab_switch 1" },
	{ on = [ "3" ], run = "tab_switch 2" },
	{ on = [ "4" ], run = "tab_switch 3" },
	{ on = [ "5" ], run = "tab_switch 4" },
	{ on = [ "6" ], run = "tab_switch 5" },
	{ on = [ "7" ], run = "tab_switch 6" },
	{ on = [ "8" ], run = "tab_switch 7" },
	{ on = [ "9" ], run = "tab_switch 8" },

	{ on = [ "[" ], run = "tab_switch -1 --relative" },
	{ on = [ "]" ], run = "tab_switch 1 --relative" },

	{ on = [ "{" ], run = "tab_swap -1" },
	{ on = [ "}" ], run = "tab_swap 1" },

	# Tasks
	{ on = [ "w" ], run = "tasks_show" },

	# Goto
	{ on = [ "g", "h" ], run = "cd ~" },
	{ on = [ "g", "c" ], run = "cd ~/.config" },
	{ on = [ "g", "d" ], run = "cd ~/Downloads" },
	{ on = [ "g", "t" ], run = "cd /tmp" },
	{ on = [ "g", "<Space>" ], run = "cd --interactive" },
]

[tasks]

keymap = [
	{ on = [ "<C-q>" ], run = "close" },
	{ on = [ "<Esc>" ], run = "close" },
	{ on = [ "w" ], run = "close" },

	{ on = [ "k" ], run = "arrow -1" },
	{ on = [ "j" ], run = "arrow 1" },

	{ on = [ "<Up>" ], run = "arrow -1" },
	{ on = [ "<Down>" ], run = "arrow 1" },

	{ on = [ "<Enter>" ], run = "inspect" },
	{ on = [ "x" ], run = "cancel" },
]

[select]

keymap = [
	{ on = [ "<C-q>" ], run = "close" },
	{ on = [ "<Esc>" ], run = "close" },
	{ on = [ "<Enter>" ], run = "close --submit" },

	{ on = [ "k" ], run = "arrow -1" },
	{ on = [ "j" ], run = "arrow 1" },

	{ on = [ "K" ], run = "arrow -5" },
	{ on = [ "J" ], run = "arrow 5" },

	{ on = [ "<Up>" ], run = "arrow -1" },
	{ on = [ "<Down>" ], run = "arrow 1" },
]

[input]

append_keymap = [
	{ on = [ "<C-g>"], run = "plugin test --sync --args='hello world'" },
	{ on = [ "<C-q>" ], run = "close" },
	{ on = [ "<Enter>" ], run = "close --submit" },
	{ on = [ "<Esc>" ], run = "escape" },
	{ on = [ "<Backspace>" ], run = "backspace" },

	# Mode
	{ on = [ "i" ], run = "insert" },
	{ on = [ "a" ], run = "insert --append" },
	{ on = [ "v" ], run = "visual" },

	# Navigation
	{ on = [ "h" ], run = "move -1" },
	{ on = [ "l" ], run = "move 1" },

	{ on = [ "0" ], run = "move -999" },
	{ on = [ "$" ], run = "move 999" },
	{ on = [ "I" ], run = [ "move -999", "insert" ] },
	{ on = [ "A" ], run = [ "move 999", "insert --append" ] },

	{ on = [ "<Left>" ], run = "move -1" },
	{ on = [ "<Right>" ], run = "move 1" },

	{ on = [ "b" ], run = "backward" },
	{ on = [ "w" ], run = "forward" },
	{ on = [ "e" ], run = "forward --end-of-word" },

	# Deletion
	{ on = [ "d" ], run = "delete --cut" },
	{ on = [ "c" ], run = "delete --cut --insert" },
	{ on = [ "x" ], run = [ "delete --cut", "move 1 --in-operating" ] },

	# Yank/Paste
	{ on = [ "y" ], run = "yank" },
	{ on = [ "p" ], run = "paste" },
	{ on = [ "P" ], run = "paste --before" },

	# Undo/Redo
	{ on = [ "u" ], run = "undo" },
	{ on = [ "<C-r>" ], run = "redo" },
]

