# you can see the mappings from yazi with ~
# it even supports search !
[manager]

# run will become run soon

# prepend before default
prepend_keymap = [
 	{ on = [ "<PageUp>" ], run = "seek -5", desc = "Seek up 5 units in the preview" },
	{ on = [ "<PageDown>" ], run = "seek 5",  desc = "Seek down 5 units in the preview" },
	# https://github.com/sxyazi/yazi/issues/1046
	{ on = [ "z" ], run = "plugin zoxide" },
	{ on = [ "Z" ], run = "plugin fzf" },
    # run  = "plugin rsync --args='user@server.com'",
    { on   = ["R"], run  = "plugin rsync", desc = "Copy files using rsync" }
]


[input]

prepend_keymap = [
	{ on = [ "<C-g>"], run = "plugin test --sync --args='hello world'" },
	{ on = [ "<C-q>" ], run = "close" },
	# { on = [ "<Enter>" ], run = "close --submit" },
	{ on = [ "<Esc>" ], run = "close", desc = "Cancel input" },
	{ on = [ "<Backspace>" ], run = "backspace" },
    { on   = [ "c", "m" ], run  = "plugin chmod", desc = "Chmod on selected files" }

]

