# This file has been generated by ./pkgs/misc/vim-plugins/update.py. Do not edit!
{ lib, buildVimPluginFrom2Nix, fetchFromGitHub, overrides ? (self: super: {}) }:
let
  packages = ( self:
{
  firenvim = buildVimPluginFrom2Nix {
    pname = "firenvim";
    version = "2021-04-25";
    src = fetchFromGitHub {
      owner = "glacambre";
      repo = "firenvim";
      rev = "32087a049f016ee0672aee400249e822c81519f1";
      sha256 = "061xp8cqmajriv9pn3dli8sx6iz844i3lgpd5v3gc38n6idjfvzv";
    };
    meta.homepage = "https://github.com/glacambre/firenvim/";
  };

  markdown-preview-nvim = buildVimPluginFrom2Nix {
    pname = "markdown-preview-nvim";
    version = "2021-03-10";
    src = fetchFromGitHub {
      owner = "iamcco";
      repo = "markdown-preview.nvim";
      rev = "e5bfe9b89dc9c2fbd24ed0f0596c85fd0568b143";
      sha256 = "0bfkcfjqg2jqm4ss16ks1mfnlnpyg1l4l18g7pagw1dfka14y8fg";
    };
    meta.homepage = "https://github.com/iamcco/markdown-preview.nvim/";
  };

  nvim-markdown-preview = buildVimPluginFrom2Nix {
    pname = "nvim-markdown-preview";
    version = "2019-01-29";
    src = fetchFromGitHub {
      owner = "davidgranstrom";
      repo = "nvim-markdown-preview";
      rev = "9914aae9c1736212f88f1893d14bfe69400443f0";
      sha256 = "1kc74y9wd6ipz82ry7c3vzi4r65b817wiwcgf7q0632qxxczqdxr";
    };
    meta.homepage = "https://github.com/davidgranstrom/nvim-markdown-preview/";
  };

  nvim-terminal-lua = buildVimPluginFrom2Nix {
    pname = "nvim-terminal-lua";
    version = "2019-10-17";
    src = fetchFromGitHub {
      owner = "norcalli";
      repo = "nvim-terminal.lua";
      rev = "095f98aaa7265628a72cd2706350c091544b5602";
      sha256 = "09hass19v3wrqgxjcr3b59w462lp2nw533zwb1nnmiz99gx1znpx";
    };
    meta.homepage = "https://github.com/norcalli/nvim-terminal.lua/";
  };

  nvim-tetris = buildVimPluginFrom2Nix {
    pname = "nvim-tetris";
    version = "2021-03-26";
    src = fetchFromGitHub {
      owner = "alec-gibson";
      repo = "nvim-tetris";
      rev = "5deb5d17e089f700b82cf37e3a8ba980752a3f23";
      sha256 = "1h235bigcnsf0j717cwzvwvk3zs66h9dfngj25p4jfd1n3c5vama";
    };
    meta.homepage = "https://github.com/alec-gibson/nvim-tetris/";
  };

  octo-nvim = buildVimPluginFrom2Nix {
    pname = "octo-nvim";
    version = "2021-04-23";
    src = fetchFromGitHub {
      owner = "pwntester";
      repo = "octo.nvim";
      rev = "9aa7d354ff4faee80fc4a766c42d319ca65e6c75";
      sha256 = "1hrxc3xb90wgnqay8cal8zafn3qbfzql9hyfgm2qy5wys6rp0ng8";
    };
    meta.homepage = "https://github.com/pwntester/octo.nvim/";
  };

  registers-nvim = buildVimPluginFrom2Nix {
    pname = "registers-nvim";
    version = "2021-04-13";
    src = fetchFromGitHub {
      owner = "tversteeg";
      repo = "registers.nvim";
      rev = "b8ad2cd8a01dc3e4c2530820409d01b1bbd6fb95";
      sha256 = "1jz41mskrrbb4w2hkxcpmnpgj93nbh2rb30mn566xkjn3zkh1r23";
    };
    meta.homepage = "https://github.com/tversteeg/registers.nvim/";
  };

  specs-nvim = buildVimPluginFrom2Nix {
    pname = "specs-nvim";
    version = "2021-04-03";
    src = fetchFromGitHub {
      owner = "edluffy";
      repo = "specs.nvim";
      rev = "a03c03ed532f679d89cc6c2f5173cc222e9fbb45";
      sha256 = "11qw45kx8v23vrs50qga07820328c9y3kmyjvyfbgkb3ayd17jxi";
    };
    meta.homepage = "https://github.com/edluffy/specs.nvim/";
  };

  vim-livedown = buildVimPluginFrom2Nix {
    pname = "vim-livedown";
    version = "2019-02-28";
    src = fetchFromGitHub {
      owner = "shime";
      repo = "vim-livedown";
      rev = "24c78c0c1177c0231bb542fa1e3807a3b089248e";
      sha256 = "0dnhxh4ifhvkp9a2vh7a97kc3dqcnh1jv3g8dlsxwy47zdhb0lnd";
    };
    meta.homepage = "https://github.com/shime/vim-livedown/";
  };

  vim-markdown-composer = buildVimPluginFrom2Nix {
    pname = "vim-markdown-composer";
    version = "2020-08-15";
    src = fetchFromGitHub {
      owner = "euclio";
      repo = "vim-markdown-composer";
      rev = "c0f98ec3d6c4cb49455c18f2aeb83c0dcbad1bc4";
      sha256 = "10vb3p8gksjy8zfzlkhirdsjwgvh1yv19plxwr404x87j393rs7n";
      fetchSubmodules = true;
    };
    meta.homepage = "https://github.com/euclio/vim-markdown-composer/";
  };

  vim-markdown-preview = buildVimPluginFrom2Nix {
    pname = "vim-markdown-preview";
    version = "2018-03-21";
    src = fetchFromGitHub {
      owner = "JamshedVesuna";
      repo = "vim-markdown-preview";
      rev = "9b3ec41fb6f0f49d9bb7ca81fa1c62a8a54b1214";
      sha256 = "04m452rfns9wxd2zmqqzjicysir6rn43yi736s05ss69wylhw2g3";
    };
    meta.homepage = "https://github.com/JamshedVesuna/vim-markdown-preview/";
  };

});
in lib.fix' (lib.extends overrides packages)
