# This file has been generated by ./pkgs/misc/vim-plugins/update.py. Do not edit!
{ lib, buildVimPluginFrom2Nix, fetchFromGitHub }:

final: prev:
{
  firenvim = buildVimPluginFrom2Nix {
    pname = "firenvim";
    version = "2021-07-06";
    src = fetchFromGitHub {
      owner = "glacambre";
      repo = "firenvim";
      rev = "b7d4133fc4d0344f6370fb54d8ab3937e1ab2ada";
      sha256 = "1mn9mqsz2d8a0sk1xlfrrrp38p192b8g02lja3f2bak9p8jvv7i2";
    };
    meta.homepage = "https://github.com/glacambre/firenvim/";
  };

  markdown-preview-nvim = buildVimPluginFrom2Nix {
    pname = "markdown-preview-nvim";
    version = "2021-03-10";
    src = fetchFromGitHub {
      owner = "iamcco";
      repo = "markdown-preview.nvim";
      rev = "e5bfe9b89dc9c2fbd24ed0f0596c85fd0568b143";
      sha256 = "0bfkcfjqg2jqm4ss16ks1mfnlnpyg1l4l18g7pagw1dfka14y8fg";
    };
    meta.homepage = "https://github.com/iamcco/markdown-preview.nvim/";
  };

  nvim-markdown-preview = buildVimPluginFrom2Nix {
    pname = "nvim-markdown-preview";
    version = "2021-05-28";
    src = fetchFromGitHub {
      owner = "davidgranstrom";
      repo = "nvim-markdown-preview";
      rev = "d7cbefc69f93f55e376c4cb9d754390028659ea2";
      sha256 = "08yk58s2f10130n20i6fgnf8iyy6pwqv6siprbc0jqrn28pllpp9";
    };
    meta.homepage = "https://github.com/davidgranstrom/nvim-markdown-preview/";
  };

  nvim-terminal-lua = buildVimPluginFrom2Nix {
    pname = "nvim-terminal-lua";
    version = "2019-10-17";
    src = fetchFromGitHub {
      owner = "norcalli";
      repo = "nvim-terminal.lua";
      rev = "095f98aaa7265628a72cd2706350c091544b5602";
      sha256 = "09hass19v3wrqgxjcr3b59w462lp2nw533zwb1nnmiz99gx1znpx";
    };
    meta.homepage = "https://github.com/norcalli/nvim-terminal.lua/";
  };

  nvim-tetris = buildVimPluginFrom2Nix {
    pname = "nvim-tetris";
    version = "2021-06-28";
    src = fetchFromGitHub {
      owner = "alec-gibson";
      repo = "nvim-tetris";
      rev = "d17c99fb527ada98ffb0212ffc87ccda6fd4f7d9";
      sha256 = "057pmqhxk2vb3vwrydzjc1170c9dcnfasfaxklykhcwcjsmlbbzv";
    };
    meta.homepage = "https://github.com/alec-gibson/nvim-tetris/";
  };

  octo-nvim = buildVimPluginFrom2Nix {
    pname = "octo-nvim";
    version = "2021-07-09";
    src = fetchFromGitHub {
      owner = "pwntester";
      repo = "octo.nvim";
      rev = "7f2fbccb9bb91d48c93a1d4567321459737740de";
      sha256 = "1vnl0whk2h38g380dp5yjnvxscp8qalsdwfyq16j0i9jv7qa2mmd";
    };
    meta.homepage = "https://github.com/pwntester/octo.nvim/";
  };

  registers-nvim = buildVimPluginFrom2Nix {
    pname = "registers-nvim";
    version = "2021-07-06";
    src = fetchFromGitHub {
      owner = "tversteeg";
      repo = "registers.nvim";
      rev = "4e79f208b4642578edcded89f889d6c76653abbd";
      sha256 = "041psdy4nsxhvfxx51anj58iac619p0dx9sp7710vvfwg526jifr";
    };
    meta.homepage = "https://github.com/tversteeg/registers.nvim/";
  };

  specs-nvim = buildVimPluginFrom2Nix {
    pname = "specs-nvim";
    version = "2021-05-05";
    src = fetchFromGitHub {
      owner = "edluffy";
      repo = "specs.nvim";
      rev = "a62319a224b73b70af47a48ba076d7ec67b08526";
      sha256 = "1hs7qp3fr451ziddv08nyygnxx1n6y32fr0y97s9zjc7j13d3nc3";
    };
    meta.homepage = "https://github.com/edluffy/specs.nvim/";
  };

  telescope-frecency-nvim = buildVimPluginFrom2Nix {
    pname = "telescope-frecency-nvim";
    version = "2021-04-18";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-frecency.nvim";
      rev = "228c7ed3ae32e90f403274f510dfc2ee21540175";
      sha256 = "1927pdr6djv8481b2bvc82wk46y0pd478gnag79dw4winhha4ibv";
    };
    meta.homepage = "https://github.com/nvim-telescope/telescope-frecency.nvim/";
  };

  telescope-fzf-native-nvim = buildVimPluginFrom2Nix {
    pname = "telescope-fzf-native-nvim";
    version = "2021-07-06";
    src = fetchFromGitHub {
      owner = "nvim-telescope";
      repo = "telescope-fzf-native.nvim";
      rev = "fe8c8d8cf7ff215ac83e1119cba87c016070b27e";
      sha256 = "0kzxf3kzw45mlccp8z5zl3cfda4n5afymmdyir3kd248ll904jy1";
    };
    meta.homepage = "https://github.com/nvim-telescope/telescope-fzf-native.nvim/";
  };

  vim-livedown = buildVimPluginFrom2Nix {
    pname = "vim-livedown";
    version = "2019-02-28";
    src = fetchFromGitHub {
      owner = "shime";
      repo = "vim-livedown";
      rev = "24c78c0c1177c0231bb542fa1e3807a3b089248e";
      sha256 = "0dnhxh4ifhvkp9a2vh7a97kc3dqcnh1jv3g8dlsxwy47zdhb0lnd";
    };
    meta.homepage = "https://github.com/shime/vim-livedown/";
  };

  vim-markdown-composer = buildVimPluginFrom2Nix {
    pname = "vim-markdown-composer";
    version = "2020-08-15";
    src = fetchFromGitHub {
      owner = "euclio";
      repo = "vim-markdown-composer";
      rev = "c0f98ec3d6c4cb49455c18f2aeb83c0dcbad1bc4";
      sha256 = "10vb3p8gksjy8zfzlkhirdsjwgvh1yv19plxwr404x87j393rs7n";
      fetchSubmodules = true;
    };
    meta.homepage = "https://github.com/euclio/vim-markdown-composer/";
  };

  vim-markdown-preview = buildVimPluginFrom2Nix {
    pname = "vim-markdown-preview";
    version = "2018-03-21";
    src = fetchFromGitHub {
      owner = "JamshedVesuna";
      repo = "vim-markdown-preview";
      rev = "9b3ec41fb6f0f49d9bb7ca81fa1c62a8a54b1214";
      sha256 = "04m452rfns9wxd2zmqqzjicysir6rn43yi736s05ss69wylhw2g3";
    };
    meta.homepage = "https://github.com/JamshedVesuna/vim-markdown-preview/";
  };

}
